import type { PresetItem, StyleDefinition } from '../types/imageNode.types';
import { getUserPresetById } from '../utils/userPresets';

export const PRESET_TABS = [
  '真实增强',
  '光照氛围',
  '镜头视角',
  '建筑表达',
  '场景配景',
  '我的收藏',
] as const;

export const MAX_MULTI_PRESETS_BY_GROUP: Partial<Record<PresetItem['group'], number>> = {
  accent_style: 2,
  architectural_representation: 1,
  camera_view: 1,
  detail_realism: 2,
  enhancement: 3,
  entourage_elements: 4,
  lighting_atmosphere: 2,
  style_state: 1,
};

const HIDDEN_SYSTEM_PRESET_IDS = new Set(['logo', 'animal_closeup']);

export function isPresetVisibleInLibrary(preset: PresetItem) {
  return preset.owner !== 'system' || !HIDDEN_SYSTEM_PRESET_IDS.has(preset.id);
}

export const PRESET_DATA: PresetItem[] = [
  // ── 真实增强（保留的旧预设） ──
  {
    id: 'photo_realistic',
    name: '照片般真实',
    title: '照片般真实',
    tabs: ['真实增强'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '真实光影 / 材质细节',
    description: '真实光影 / 材质细节',
    shortHelp: '提升整体真实度，让画面更接近真实建筑摄影或高质量建筑可视化成片。',
    detailDescription:
      '整体会提升画面的真实度，使结果更接近真实建筑摄影或高质量建筑可视化成片。系统会优先增强自然光影、真实材质、曝光关系、反射细节和建筑表皮质感，同时尽量保留原有建筑主体、构图和主要设计特征。画面不应表现得过度梦幻、过度锐利或明显 AI 化，而应呈现更克制、更可信、更适合展示与汇报的真实效果。',
    keywords: ['真实光影', '自然曝光', '材质细节', '建筑摄影感', '降低 AI 感'],
    promptTemplate: '将当前建筑画面提升为照片级真实效果，尽量保留原图主体、构图比例、体块关系和关键设计细节。增强自然光影、真实材质、空间层次、投影关系和环境融合度，使画面接近高质量建筑摄影或专业建筑可视化成片。保持天空、地面、植被、道路和周边环境自然统一，避免拼贴感和不合理阴影。保持色彩自然克制，避免过度锐化、过度饱和、梦幻化或改变建筑方案。',
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['照片', '真实', '写实'],
    thumbnail: '/assets/presets/prompt/photo-realistic.webp',
  },
  {
    id: 'artistic_realism',
    name: '艺术化处理',
    title: '艺术化处理',
    tabs: ['真实增强'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '克制艺术感 / 高级表达',
    description: '克制艺术感 / 高级表达',
    shortHelp: '在保留建筑主体和构图的基础上，增强画面的艺术表现、空间情绪和视觉完成度。',
    detailDescription:
      '整体会让画面在真实基础上更具艺术化表达，而不是单纯追求照片复刻。系统会强化光影层次、色彩控制、空间氛围、画面留白和建筑与环境之间的关系，让结果更适合概念表达、方案展示和高级建筑视觉呈现。画面应保持克制、自然、有审美，不应变成插画、梦幻图或过度风格化效果。',
    keywords: ['克制艺术感', '空间情绪', '高级表达', '柔和光影', '建筑与环境融合'],
    promptTemplate: '在保留建筑主体、构图比例、体块关系和关键设计细节的基础上，提升画面的艺术表现力和完成度。强化光影氛围、色彩层次、画面节奏、空间深度和材质表现，使结果更像经过精心控制的高质量建筑可视化作品。画面可以更有审美取向和视觉张力，但需要保持建筑逻辑真实可信。避免过度绘画化、夸张变形、杂乱元素或改变建筑设计本身。',
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['艺术化', '高级表达', '空间情绪'],
    thumbnail: '/assets/presets/prompt/artistic-realism.webp',
  },
  {
    id: 'cinematic_narrative',
    name: '电影感叙事',
    title: '电影感叙事',
    tabs: ['真实增强'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '电影光影 / 情绪叙事',
    description: '电影光影 / 情绪叙事',
    shortHelp: '增强电影化光影、冷暖关系、空间故事感和画面情绪，让建筑图更有叙事张力。',
    detailDescription:
      '整体会让画面更具电影感和叙事性。系统会强化光影方向、明暗层次、冷暖对比、前中后景关系和人物活动带来的场景故事感。建筑仍然是主体，但画面不只是展示建筑，而是呈现一种时间、情绪和空间事件。结果应更有镜头感、氛围张力和视觉记忆点，同时避免变成过度戏剧化或虚假的电影海报。',
    keywords: ['电影光影', '冷暖对比', '空间叙事', '情绪氛围', '镜头感'],
    promptTemplate: '将当前建筑画面调整为更具电影感和叙事氛围的视觉效果。增强光影方向、明暗对比、空间深度、镜头感和情绪表达，让画面更有场景感和观看吸引力。可以使用更有控制感的色彩关系和氛围光，但需要保持建筑主体、构图逻辑和主要设计元素稳定。避免过度戏剧化、画面过暗、人物喧宾夺主或偏离建筑表达。',
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['电影感', '叙事', '光影'],
    thumbnail: '/assets/presets/prompt/cinematic-narrative.webp',
  },

  // ── 新增：真实增强 ──
  {
    id: "view_to_render",
    name: "视图转渲染",
    title: "视图转渲染",
    tabs: ["真实增强"],
    category: "realism",
    group: "enhancement",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "enhancement",
    shortDescription: "草图 / 白模 / 视口转效果图",
    description: "将基础视图、草图、白模或视口图像转为建筑可视化效果图。",
    shortHelp: "适合把初步设计图快速提升为可视化表达。",
    promptTemplate: "将当前草图、白模、视口截图或初步方案图转化为更完整的建筑可视化渲染效果。保留原有建筑体块、相机角度、构图比例和主要设计关系，补充真实材质、自然光影、环境氛围和基础配景。画面应从概念表达提升为专业建筑表现图，同时避免重设计建筑、改变方案逻辑或加入无关元素。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["渲染", "白模", "视口"],
    thumbnail: '/assets/presets/prompt/view-to-render.webp',
  },

  {
    id: "add_realism",
    name: "真实细节增强",
    title: "真实细节增强",
    tabs: ["真实增强"],
    category: "realism",
    group: "enhancement",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "enhancement",
    shortDescription: "真实光影 / 材质细节 / 空间层次",
    description: "提升照片般真实度、材质、光影和空间层次。",
    shortHelp: "让画面更接近建筑摄影或高质量 ArchViz 成片。",
    promptTemplate: "在不改变原有建筑方案和构图的基础上，增强画面的真实细节和完成度。重点提升材质纹理、阴影层次、反射关系、边缘细节、植物真实感和环境融合度，使画面更接近可信的建筑可视化成片。避免过度锐化、过度饱和、脏乱细节或把画面整体改成另一种风格。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["真实", "光影", "材质"],
    thumbnail: '/assets/presets/prompt/add-realism.webp',
  },

  {
    id: "night",
    name: "夜景表现",
    title: "夜景表现",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "月光 / 室内灯光 / 夜间氛围",
    description: "将白天场景转换为真实夜景建筑表现。",
    shortHelp: "适合制作冷暖对比、灯光层次丰富的夜景图。",
    promptTemplate: "将当前建筑画面调整为真实可信的夜景表现。保留建筑主体、构图比例和空间关系，增强夜空氛围、室内外灯光层次、暖色窗光、地面反射和暗部细节。整体应有清晰的建筑可读性和舒适的夜间氛围，避免画面过暗、霓虹化、灯光过曝或变成商业海报效果。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["夜景", "灯光", "月光"],
    thumbnail: '/assets/presets/prompt/night.webp',
  },

  {
    id: "rain",
    name: "雨天氛围",
    title: "雨天氛围",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "湿润地面 / 阴天柔光 / 反射",
    description: "增加真实雨天、湿地反射和低对比氛围。",
    shortHelp: "适合营造安静、柔和、具有空气感的雨天建筑画面。",
    promptTemplate: "将当前建筑画面调整为雨天或雨后氛围。保留建筑主体、构图比例和关键设计细节，增强阴天漫射光、湿润地面反射、空气水汽、柔和对比和环境统一感。画面应呈现真实的雨后建筑场景，而不是夸张暴雨效果，避免主体被雨雾遮挡、反射不合理或画面过脏。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["雨天", "湿地", "反射"],
    thumbnail: '/assets/presets/prompt/rain.webp',
  },

  {
    id: "macro_closeup",
    name: "微距特写",
    title: "微距特写",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "材质纹理 / 构造节点 / 浅景深",
    description: "聚焦材料细节、接缝、边缘或构造节点。",
    shortHelp: "适合表达材料、工艺、节点和细节质感。",
    promptTemplate: "将画面转为建筑局部构造或材料节点的近距离特写。重点聚焦立面节点、材料交接、表皮肌理、结构细部或光影落点，同时保留与原建筑设计一致的材质逻辑和空间语境。画面应具有清晰的建筑细节表达和真实摄影感，避免变成无关物体特写、过度虚化或失去建筑属性。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["微距", "材质", "细节"],
    thumbnail: '/assets/presets/prompt/macro-closeup.webp',
  },

  {
    id: "activity_closeup",
    name: "活动近景",
    title: "活动近景",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "人物活动 / 生活场景 / 空间使用",
    description: "聚焦建筑环境中的日常活动和人物互动。",
    shortHelp: "适合表现空间被使用的真实生活感。",
    promptTemplate: "将画面调整为更接近建筑空间使用状态的活动近景。保留建筑环境、空间尺度和关键设计细节，突出人在场地中的自然行为、互动关系、动线和生活氛围，使建筑空间更有使用感。避免人物喧宾夺主、姿态夸张、遮挡主体或变成单纯人物摄影。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["活动", "人物", "近景"],
    thumbnail: '/assets/presets/prompt/activity-closeup.webp',
  },

  {
    id: "object_closeup",
    name: "物体特写",
    title: "物体特写",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "家具 / 灯具 / 装置 / 景观小品",
    description: "聚焦场景中的建筑物体、家具或设计细节。",
    shortHelp: "适合强调局部物件和空间细节。",
    promptTemplate: "将画面聚焦到建筑场景中的具体物体或空间小品，例如家具、灯具、装置、景观石、座椅、入口细节或室内陈设。保留原有建筑环境的材质、光影和空间关系，使物体特写自然服务于整体建筑氛围。画面应像建筑摄影中的局部场景特写，避免把物体变成孤立产品图或改变建筑主体表达。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["物体", "家具", "细节"],
    thumbnail: '/assets/presets/prompt/object-closeup.webp',
  },

  {
    id: "animal_closeup",
    name: "动物特写",
    title: "动物特写",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "自然行为 / 场景融入 / 生活气息",
    description: "在建筑或景观环境中创建自然动物近景。",
    shortHelp: "适合特殊自然场景、景观氛围或生活化表达。",
    promptTemplate: "在当前建筑或景观场景中加入少量自然出现的动物元素，用于增强生活气息、尺度感和环境氛围。动物应与场地功能、透视比例、光影方向和画面风格自然融合，并保持建筑或景观仍然是画面主体。避免动物过大、过多、姿态夸张、遮挡建筑主体或让画面变成动物主题图。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["动物", "自然", "近景"],
    thumbnail: '/assets/presets/prompt/animal-closeup.webp',
  },

  {
    id: "moodboard",
    name: "情绪板",
    title: "情绪板",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "材料样板 / 色彩 / 设计氛围",
    description: "根据原图材料和色调生成高端建筑情绪板。",
    shortHelp: "适合整理材料、色彩、质感和氛围参考。",
    promptTemplate: "基于当前建筑项目生成更偏材料、色彩和氛围整理的情绪板表达。保留原项目的设计方向和视觉气质，提取建筑材质、色彩关系、光影氛围、景观元素和参考细节，形成清晰、有秩序的视觉灵感展示。结果应服务于方案表达和风格沟通，避免重新设计项目、加入无关素材或变成普通拼贴海报。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["情绪板", "材料", "色彩"],
    thumbnail: '/assets/presets/prompt/moodboard.webp',
  },

  {
    id: "design_board",
    name: "设计板",
    title: "设计板",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "汇报图面 / 作品集 / 版式",
    description: "将项目整理为高级建筑方案展示板。",
    shortHelp: "适合生成客户汇报、作品集或 Behance 风格图面。",
    promptTemplate: "将当前建筑项目整理为更完整的设计展示板效果。保留原有建筑主体、构图比例、空间关系和关键设计信息，通过清晰的版式、图像层级、辅助说明和视觉节奏提升项目表达。画面应像专业建筑方案展示板，重点突出设计逻辑和视觉完成度，避免重设计建筑、过度装饰或让版式喧宾夺主。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["设计板", "汇报", "作品集"],
    thumbnail: '/assets/presets/prompt/design-board.webp',
  },

  {
    id: "blueprints",
    name: "蓝图风格",
    title: "蓝图风格",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "技术图纸 / 线稿 / 制图感",
    description: "转换为建筑蓝图或专业技术图纸风格。",
    shortHelp: "适合表达结构、比例、线稿和技术感。",
    promptTemplate: "将当前建筑画面转换为蓝图或技术图纸风格表达。保留建筑主体轮廓、构图比例、空间关系和主要设计信息，以线稿、图纸质感、蓝色调和清晰的结构边界呈现建筑逻辑。结果应像专业建筑制图或概念表达，避免过度装饰、文字混乱、细节丢失或改变建筑方案。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["蓝图", "图纸", "线稿"],
    thumbnail: '/assets/presets/prompt/blueprints.webp',
  },

  {
    id: "axonometry",
    name: "轴测图",
    title: "轴测图",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "三维剖切 / 正交投影 / 空间结构",
    description: "将场景转换为建筑轴测表达。",
    shortHelp: "适合展示体块、结构、空间关系和设计逻辑。",
    promptTemplate: "将当前建筑画面转换为清晰的轴测表达效果。保留原有建筑体块、空间组织、场地关系和关键设计信息，以更规整的正交视角展示建筑结构、层级和空间逻辑。画面应具有专业建筑图解感和可读性，避免透视混乱、体块变形、信息过载或改变设计方案。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["轴测", "剖切", "空间"],
    thumbnail: '/assets/presets/prompt/axonometry.webp',
  },

  {
    id: "clean_up",
    name: "清理画面",
    title: "清理画面",
    tabs: ["真实增强"],
    category: "realism",
    group: "enhancement",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "enhancement",
    shortDescription: "去杂物 / 修瑕疵 / 保持原图",
    description: "清理杂乱元素、AI 错误、污点和干扰项。",
    shortHelp: "让画面更干净、专业，但不改变设计。",
    promptTemplate: "清理当前建筑画面中的杂乱元素、视觉噪点、临时物体、瑕疵和不必要干扰，使画面更干净、完整和专业。保留建筑主体、构图比例、体块关系、材质逻辑和关键设计细节，只优化影响画面完成度的杂乱内容。避免过度磨皮、细节丢失、画面变空或改变建筑方案。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["清理", "修复", "干净"],
    thumbnail: '/assets/presets/prompt/clean-up.webp',
  },

  {
    id: "drone_view",
    name: "航拍视角",
    title: "航拍视角",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "高空视角 / 场地关系 / 鸟瞰",
    description: "将相机移动到高空航拍视角。",
    shortHelp: "适合展示场地、体块、景观和周边关系。",
    promptTemplate: "将当前建筑画面调整为更高视角的航拍或鸟瞰表现。保留建筑主体识别度、场地边界、总体布局和主要空间关系，增强屋顶、道路、景观和周边环境之间的整体联系。画面应具有清晰的规划尺度和空间可读性，避免主体过小、透视失真或改变建筑方案。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["航拍", "鸟瞰", "场地"],
    thumbnail: '/assets/presets/prompt/drone-view.webp',
  },

  {
    id: "unfinished",
    name: "未完成效果",
    title: "未完成效果",
    tabs: ["真实增强"],
    category: "realism",
    group: "enhancement",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "施工中 / 毛坯 / 原始结构",
    description: "将场景转换为真实未完成施工状态。",
    shortHelp: "适合表达施工中、毛坯、概念阶段或未交付状态。",
    promptTemplate: "将当前建筑画面调整为真实的施工中或未完成状态。保留建筑体块、构图比例、空间关系和主要设计逻辑，加入适度的裸露结构、临时材料、施工痕迹、未完成表面和现场氛围。效果应像真实建筑施工阶段或方案过程图，避免废墟化、破败化、脏乱过度或改变建筑设计。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["施工", "毛坯", "未完成"],
    thumbnail: '/assets/presets/prompt/unfinished.webp',
  },

  {
    id: "artificial_light",
    name: "人工照明",
    title: "人工照明",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "灯带 / 筒灯 / 景观灯",
    description: "增强室内外人工照明和空间层次。",
    shortHelp: "适合让空间更温暖、更有层次和完成度。",
    promptTemplate: "将当前建筑画面调整为更真实的人工照明效果。保留建筑主体、构图比例和空间关系，增强室内灯光、立面照明、景观灯、道路灯或重点光源的层次，使光线衰减、反射和暗部细节更加自然。整体应呈现可信的夜间或室内照明氛围，避免灯光过曝、色彩混乱、霓虹化或改变建筑设计。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["照明", "灯光", "LED"],
    thumbnail: '/assets/presets/prompt/artificial-light.webp',
  },

  {
    id: "night_to_day",
    name: "夜景转白天",
    title: "夜景转白天",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "白天日光 / 清晰材质 / 自然曝光",
    description: "将夜景或暗光场景转换为自然白天效果。",
    shortHelp: "适合把夜景图恢复成清晰白天建筑表现。",
    promptTemplate: "将当前夜景建筑画面转换为真实自然的白天效果。保留建筑主体、构图比例、空间关系和关键设计细节，去除夜间灯光主导感，补充自然日光、天空亮度、材质色彩、环境细节和合理阴影。画面应像可信的白天建筑场景，避免残留强烈夜景灯光、过曝、色彩漂移或改变建筑方案。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["白天", "日光", "转换"],
    thumbnail: '/assets/presets/prompt/night-to-day.webp',
  },

  {
    id: "golden_hour",
    name: "黄金时刻",
    title: "黄金时刻",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "低角度暖光 / 长阴影 / 日落氛围",
    description: "将画面调整为黄金时刻建筑氛围。",
    shortHelp: "适合营造温暖、高级、具有空间层次的黄昏光感。",
    promptTemplate: "将当前建筑画面调整为温暖柔和的黄金时刻氛围。保留建筑主体、构图比例、体块关系和关键设计细节，增强低角度阳光、长阴影、暖色高光、柔和天空和空间层次。画面应具有自然的日落前后光感和高级建筑摄影气质，避免过度橙黄、阴影不合理或改变建筑方案。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["黄金时刻", "黄昏", "暖光"],
    thumbnail: '/assets/presets/prompt/golden-hour.webp',
  },

  {
    id: "make_brighter",
    name: "提亮画面",
    title: "提亮画面",
    tabs: ["真实增强"],
    category: "realism",
    group: "enhancement",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "enhancement",
    shortDescription: "提升曝光 / 保留层次",
    description: "轻微提亮画面，提高可见度和清晰度。",
    shortHelp: "适合画面偏暗但不想改变原氛围时使用。",
    promptTemplate: "在保留当前建筑主体、构图比例和原有氛围的基础上，适度提亮画面。增强暗部可读性、材质细节、空间层次和整体通透感，同时保留合理阴影、光照方向和明暗关系。避免过曝、灰白失真、对比完全消失或把画面改成另一种时间氛围。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["提亮", "曝光", "清晰"],
    thumbnail: '/assets/presets/prompt/make-brighter.webp',
  },

  {
    id: "add_people",
    name: "添加人物",
    title: "添加人物",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "尺度人物 / 空间使用 / 生活感",
    description: "添加真实人物，增强空间尺度和活动氛围。",
    shortHelp: "适合让建筑场景更有尺度感和生活感。",
    promptTemplate: "在当前建筑场景中加入适量自然活动的人物，用于增强空间尺度、使用氛围和生活感。人物应符合场地功能、透视关系、光影方向和画面风格，与建筑环境自然融合。避免人物过多、姿态夸张、遮挡建筑主体或变成画面主角。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["人物", "尺度", "生活感"],
    thumbnail: '/assets/presets/prompt/add-people.webp',
  },

  {
    id: "blurred_people",
    name: "模糊人物",
    title: "模糊人物",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "运动模糊 / 街景活动 / 动态感",
    description: "添加轻微运动模糊人物，增强真实活动感。",
    shortHelp: "适合街道、公共空间、商业空间等场景。",
    promptTemplate: "在当前建筑场景中加入适量带有运动模糊或弱化处理的人物，用于表现空间使用和真实街区氛围。人物应自然分布在合理动线上，尺度、透视和光影与原场景一致，并保持建筑主体清晰。避免人物过密、模糊过重、遮挡关键设计或造成杂乱感。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["人物", "模糊", "动态"],
    thumbnail: '/assets/presets/prompt/blurred-people.webp',
  },

  {
    id: "add_cars",
    name: "添加车辆",
    title: "添加车辆",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "车辆尺度 / 城市环境 / 停车落客",
    description: "添加真实车辆作为尺度和场景配景。",
    shortHelp: "适合道路、街景、住宅、商业和入口场景。",
    promptTemplate: "在当前建筑场景中加入少量符合道路、入口或停车区域逻辑的车辆，用于增强真实城市环境和尺度感。车辆应匹配画面透视、光影、材质反射和场景风格，不影响建筑主体表达。避免车辆过多、比例错误、位置不合理或产生商业广告感。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["车辆", "尺度", "街景"],
    thumbnail: '/assets/presets/prompt/add-cars.webp',
  },

  {
    id: "blurred_cars",
    name: "模糊车辆",
    title: "模糊车辆",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "运动车辆 / 街道动态 / 城市感",
    description: "添加轻微运动模糊车辆，增强街道动态感。",
    shortHelp: "适合表现城市道路、商业街或交通氛围。",
    promptTemplate: "在当前建筑场景中加入适量带有轻微运动模糊的车辆，用于表现道路流动感和真实城市氛围。车辆应沿合理交通方向出现，透视、尺度、光影和反射关系需要与原图一致。避免模糊过强、遮挡建筑主体、车辆过密或让画面变得杂乱。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["车辆", "模糊", "动态"],
    thumbnail: '/assets/presets/prompt/blurred-cars.webp',
  },

  {
    id: "autumn",
    name: "秋季氛围",
    title: "秋季氛围",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "暖棕色 / 落叶 / 柔和空气",
    description: "将场景转换为真实秋季建筑氛围。",
    shortHelp: "适合营造温暖、成熟、略带湿润的秋季场景。",
    promptTemplate: "将当前建筑画面调整为自然克制的秋季氛围。保留建筑主体、构图比例和空间关系，增强暖棕色植被、落叶、柔和阳光、低饱和色彩和季节性的环境细节。整体应呈现真实的秋季建筑场景，避免颜色过艳、落叶过多、季节元素喧宾夺主或遮挡建筑主体。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["秋季", "落叶", "暖棕"],
    thumbnail: '/assets/presets/prompt/autumn.webp',
  },

  {
    id: "winter",
    name: "冬季氛围",
    title: "冬季氛围",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "雪景 / 冷色日光 / 冬季空气",
    description: "将场景转换为真实冬季建筑氛围。",
    shortHelp: "适合表现冷静、干净、具有季节感的冬季建筑画面。",
    promptTemplate: "将当前建筑画面调整为真实自然的冬季氛围。保留建筑主体、构图比例、体块关系和主要空间结构，加入适度的冷色天光、冬季植被、薄雪或积雪痕迹，并保持地面、屋顶和周边环境的逻辑一致。整体应清冷、安静、克制，避免奇幻雪景、过厚积雪、主体遮挡或改变建筑方案。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["冬季", "雪", "冷色"],
    thumbnail: '/assets/presets/prompt/winter.webp',
  },

  {
    id: "fog",
    name: "雾气氛围",
    title: "雾气氛围",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "空气透视 / 柔和层次 / 薄雾",
    description: "增加真实雾气和空间层次。",
    shortHelp: "适合增强空气感、深度和柔和情绪。",
    promptTemplate: "将当前建筑画面加入真实的雾气或薄雾氛围。保留建筑主体、构图比例和主要空间关系，通过空气透视、低对比度、柔和远景和湿润光感增强画面的层次与安静感。建筑主体仍需保持清晰可读，避免雾气过厚、细节完全丢失、画面脏灰或变成奇幻场景。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["雾气", "空气感", "层次"],
    thumbnail: '/assets/presets/prompt/fog.webp',
  },

  {
    id: "volumetric",
    name: "体积光",
    title: "体积光",
    tabs: ["光照氛围"],
    category: "atmosphere",
    group: "lighting_atmosphere",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "光束 / 空气颗粒 / 戏剧光影",
    description: "增加穿过树木、开口或建筑构件的体积光。",
    shortHelp: "适合增强空间戏剧性和空气感。",
    promptTemplate: "在当前建筑画面中增强真实的体积光效果。保留建筑主体、构图比例和光源方向，使阳光或人工光穿过空气、窗洞、树影或空间缝隙，形成有方向感的光束、空气颗粒和空间层次。效果应克制并服务于建筑氛围，避免光束过强、方向混乱、舞台化或遮挡关键设计。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["体积光", "光束", "空气"],
    thumbnail: '/assets/presets/prompt/volumetric.webp',
  },

  {
    id: "add_birds",
    name: "添加飞鸟",
    title: "添加飞鸟",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "天空细节 / 自然生气",
    description: "在天空中添加少量远景飞鸟。",
    shortHelp: "适合让天空更自然，但不抢建筑主体。",
    promptTemplate: "在当前建筑画面的天空或远景中加入少量自然飞鸟，用于增强空间尺度、空气感和场景生动性。飞鸟应分布克制，大小、远近和方向符合画面透视，不影响建筑主体和构图重点。避免飞鸟过多、过大、排列僵硬或产生装饰贴图感。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["飞鸟", "天空", "自然"],
    thumbnail: '/assets/presets/prompt/add-birds.webp',
  },

  {
    id: "add_flowers",
    name: "添加花卉",
    title: "添加花卉",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "花境 / 种植细节 / 景观层次",
    description: "在景观区域添加真实花卉和种植细节。",
    shortHelp: "适合增强景观精致度和季节感。",
    promptTemplate: "在当前建筑或景观场景中加入适量自然花卉，用于丰富前景、花池、道路边缘或庭院区域的季节感和细节层次。花卉应符合场地尺度、光影方向和景观设计逻辑，与草地、铺装和建筑环境自然衔接。避免颜色过艳、密度过高、遮挡建筑主体或变成花卉主题图。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["花卉", "花境", "景观"],
    thumbnail: '/assets/presets/prompt/add-flowers.webp',
  },

  {
    id: "add_grass",
    name: "添加草地",
    title: "添加草地",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "草坪 / 地被 / 软景观",
    description: "添加或增强真实草地、地被和软质景观。",
    shortHelp: "适合让场地和景观地面更自然。",
    promptTemplate: "在当前建筑场景中增强或补充自然草地，使地面景观更真实、柔和并具有空间层次。草地应符合原有场地边界、地形、光影和透视关系，与铺装、植物和建筑基座自然融合。避免草地过度茂密、边缘不合理、颜色过饱和或覆盖重要建筑信息。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["草地", "地被", "景观"],
    thumbnail: '/assets/presets/prompt/add-grass.webp',
  },

  {
    id: "add_trees",
    name: "添加树木",
    title: "添加树木",
    tabs: ["场景配景"],
    category: "environment",
    group: "entourage_elements",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "树木层次 / 绿化 / 自然框景",
    description: "添加或增强真实树木和景观植被。",
    shortHelp: "适合增强场地层次、景深和自然环境。",
    promptTemplate: "在当前建筑场景中加入或增强适量树木，用于丰富景观层次、空间尺度和环境氛围。树木应符合场地位置、透视比例、季节特征和光影方向，并与建筑体量保持合理关系。避免树木遮挡主要立面、数量过多、比例失真或像后期贴图。",
    recommendedInCommon: true,
    userFavorite: false,
    tags: ["树木", "绿化", "景观"],
    thumbnail: '/assets/presets/prompt/add-trees.webp',
  },

  {
    id: "logo",
    name: "添加标志",
    title: "添加标志",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "品牌标识 / 项目标志 / 图形提炼",
    description: "基于建筑或主体物生成简洁 2D 标志。",
    shortHelp: "适合项目汇报、品牌概念或图形化表达。",
    promptTemplate: {
      goal: "基于图像中的主体物体、建筑或设计身份，创建一个干净的 2D 标志。",
      style: "极简、几何、专业平面设计风格，适合建筑品牌或项目展示。",
      image: "提取原建筑或主体物的核心轮廓、比例、形体关系或设计特征作为图形灵感。",
      background: "使用干净背景，让标志本身清晰可读。",
      output: "输出为简洁、易识别、比例平衡的 2D 标志设计。",
      constraints: "不要生成复杂插画，不要加入无意义文字，不要过度装饰，不要偏离原主体的设计身份。",
    },
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["标志", "品牌", "图形"],
    thumbnail: '/assets/presets/prompt/logo.webp',
  },

  {
    id: "mockup",
    name: "模型展示",
    title: "模型展示",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "建筑模型 / 桌面展示 / 浅景深",
    description: "将空间或建筑转为建筑模型展示近景。",
    shortHelp: "适合表现实体模型、汇报桌面和设计展示感。",
    promptTemplate: "将当前建筑项目转译为建筑模型展示效果。保留原有建筑体块、比例关系、空间结构和关键设计特征，使画面呈现为实体模型、沙盘模型或工作室模型摄影的质感。重点表现材料尺度、边缘细节、光影和模型感，避免重设计建筑、比例失真或变成玩具化效果。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["模型", "mockup", "展示"],
    thumbnail: '/assets/presets/prompt/mockup.webp',
  },

  {
    id: "make_sketch",
    name: "转为草图",
    title: "转为草图",
    tabs: ["建筑表达"],
    category: "environment",
    group: "architectural_representation",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "铅笔线稿 / 概念草图 / 手绘感",
    description: "将图像转换为精致建筑草图。",
    shortHelp: "适合方案概念表达、早期设计和图面风格转换。",
    promptTemplate: "将当前建筑画面转换为建筑设计草图或手绘概念表达。保留原有建筑体块、构图比例、空间关系和关键设计细节，用自然线条、轻微笔触、明暗层次和材料暗示来表达方案。画面应像建筑师的设计草图或概念推敲图，避免过度漫画化、线条杂乱、结构变形或丢失主体信息。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["草图", "线稿", "手绘"],
    thumbnail: '/assets/presets/prompt/make-sketch.webp',
  },

  {
    id: "side_view",
    name: "侧视图",
    title: "侧视图",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "右侧视角 / 立面感 / 侧向观察",
    description: "将相机移动到右侧视角观察空间或物体。",
    shortHelp: "适合查看侧向体块、立面关系或横向空间。",
    promptTemplate: "将当前建筑画面调整为更清晰的侧向视角表达。保留建筑主体、体块比例、立面逻辑和关键设计细节，使侧立面、进深关系、开窗节奏和材料层次更加明确。画面应像稳定的建筑摄影或方案表达视角，避免过度旋转、透视混乱、结构变形或丢失主要空间关系。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["侧视", "视角", "立面"],
    thumbnail: '/assets/presets/prompt/side-view.webp',
  },

  {
    id: "top_view",
    name: "顶视图",
    title: "顶视图",
    tabs: ["镜头视角"],
    category: "perspective",
    group: "camera_view",
    selectType: "multi",
    selectionMode: "multi",
    owner: "system",
    presetType: "modifier",
    shortDescription: "俯视 / 总平 / 平面关系",
    description: "从顶部俯视角展示空间或场地。",
    shortHelp: "适合查看总平、空间组织和家具布置关系。",
    promptTemplate: "将当前建筑画面调整为顶视或接近总平面的表达方式。保留建筑轮廓、场地边界、空间布局、道路关系和景观组织，使整体平面结构和场地逻辑更加清晰。结果应有建筑总平或规划表达的可读性，避免主体过度扁平、信息混乱、比例失真或改变方案布局。",
    recommendedInCommon: false,
    userFavorite: false,
    tags: ["顶视", "俯视", "总平"],
    thumbnail: '/assets/presets/prompt/top-view.webp',
  },
];

const PRESET_BY_ID = new Map(PRESET_DATA.map((preset) => [preset.id, preset]));

export function getPresetById(id: string) {
  return PRESET_BY_ID.get(id) || getUserPresetById(id);
}

export const nordicAtmosphereStyle: StyleDefinition = {
  id: 'nordic_atmosphere',
  title: '北欧氛围感',
  shortDescription: '低饱和 / 诗意氛围 / 柔和自然光',
  coverImage: '/assets/styles/nordic_atmosphere/cover.webp',
  detailedDescription:
    '北欧氛围感强调低饱和、冷灰调、柔和自然光和强烈的环境氛围。画面不追求商业效果图式的高清锐利，而是营造一种诗意、冷静、内敛、略带忧郁的建筑图像气质。\n\n建筑应与地形、植物、天空、雾气、雨雪、水体等自然环境深度融合，而不是像单独摆放在场景中的物体。画面通常采用阴天、薄雾、漫射光、侧光、逆光或冬季感光线，避免强烈直射阳光、纯净蓝天和过高饱和度。\n\n整体质感偏向绘画感与自然主义，更接近高级建筑摄影与数字手绘合成之间的状态。材质表现应真实但克制，不夸张、不塑料感、不强 HDR。人物和活动元素应尽量少且处理克制，重点仍然是建筑在环境中的存在感与时间感。',
  tags: ['低饱和', '冷灰调', '阴天漫射光', '薄雾空气感', '绘画感', '建筑融于环境', '冷静叙事', '北欧气质'],
  promptTemplate: {
    styleCore: '高度氛围化的建筑可视化表达，强调北欧自然主义气质、诗意叙事感和柔和绘画感，不追求硬质商业CG效果。',
    color: '使用低饱和、冷灰调、克制的自然色彩关系，避免鲜艳、高饱和和地产广告式配色。',
    lighting: '采用柔和自然光、阴天漫射光、侧光、逆光或雾中光感，避免强烈直射阳光和生硬阴影。',
    atmosphere: '营造安静、冷静、略带忧郁的环境氛围，允许轻微薄雾、空气透视和柔和颗粒感。',
    architectureEnvironment: '强调建筑与自然环境、景观、地形、植物、天空、水体的深度融合，让建筑像已经在场地中存在很久。',
    composition: '保持克制、冷静、电影化的构图，强调空间层次、环境包裹感和建筑摄影式视角。',
    material: '材质真实但柔和，不要过度锐化、过度反光、过强CG塑料感。',
    entourage: '人物和配景元素应克制，数量少，避免喧宾夺主，重点服务建筑与场景氛围。',
    avoid: '避免纯蓝天大晴天、过高饱和、商业地产广告感、塑料CG感、夸张HDR、过强锐化、人物过多、舞台式强打光。',
  },
};

export const conceptualDramaStyle: StyleDefinition = {
  id: 'conceptual_drama',
  title: '概念戏剧感',
  shortDescription: '强对比 / 概念叙事 / 戏剧化冲击',
  coverImage: '/assets/styles/conceptual_drama/cover.webp',
  detailedDescription:
    '概念戏剧感强调强烈的视觉冲击力、概念叙事和电影化光影。画面不只是展示建筑外观，而是将建筑放入一个具有情绪、事件和故事张力的场景中，让建筑成为画面中的视觉主角和叙事核心。\n\n与冷静、低饱和、自然主义的氛围不同，概念戏剧感更偏向大胆、外放、艺术化和戏剧化的表达。画面可以使用更强烈的明暗反差、更鲜明的冷暖对比、更有表现力的天空、云层、烟雾、逆光、城市活动或超现实氛围，用来放大设计概念和空间情绪。\n\n这种风格适合让建筑图像更有传播性、记忆点和概念冲击力。人物、车辆、灯光、天气和城市配景可以更积极地参与画面叙事，但必须服务于建筑主体，不能让画面变得混乱或把建筑淹没。最终效果应接近一张高质量的建筑电影海报：有张力、有故事、有视觉中心，同时仍然保持建筑可视化的空间可信度和设计表达清晰度。',
  tags: ['戏剧光影', '强对比', '概念叙事', '电影感', '视觉冲击', '大胆色彩', '城市事件', '海报感'],
  promptTemplate: {
    styleCore: '戏剧化、概念叙事导向的建筑可视化表达，强调强烈视觉冲击、电影化场景、情绪张力和设计概念的视觉放大。建筑必须保持清晰主体地位，而不是被环境元素淹没。',
    color: '使用更大胆、更有表现力的色彩关系，允许强烈冷暖对比、深蓝阴影、橙红天空、霓虹色点缀、浓郁黄昏或夜景色调。色彩可以鲜明但必须高级、受控，避免廉价过饱和和杂乱配色。',
    lighting: '采用强烈戏剧化光影，例如强侧光、逆光、轮廓光、局部聚焦光、夜景灯光、体积光、穿透云层的光束或高反差环境光。光线应强化建筑体量、边缘轮廓、空间深度和画面张力。',
    atmosphere: '营造充满能量、事件感和故事性的画面氛围。可以加入戏剧化天空、厚重云层、烟雾、雨雪、湿润地面、反射、光束、城市活动或轻微超现实元素，让画面具有记忆点和传播感。',
    architectureEnvironment: '建筑应作为视觉故事的核心角色，与城市环境、人群活动、交通、天气、景观、灯光和场地事件形成完整叙事。环境元素可以丰富，但必须围绕建筑展开，不能遮挡或削弱建筑主体。',
    composition: '使用电影化、海报化、具有强视觉中心的构图。允许大胆透视、前景遮挡、强剪影、动态人群、低机位、广角张力和富有冲击力的画面布局，但仍需保持建筑形体、比例和空间关系清晰。',
    material: '材质表现应保持可信，同时可以通过更强的高光、反射、湿润地面、夜景灯光、金属与玻璃反射、局部明暗对比来增强表现力。避免塑料感、廉价CG质感和无细节的大面积假材质。',
    entourage: '人物、车辆、活动、城市配景和环境细节可以比克制风格更积极地出现，用来制造事件感和画面故事。但数量、位置和明暗关系必须受控，不能造成杂乱，也不能抢走建筑主体的注意力。',
    avoid: '避免平淡光照、低对比、灰暗无重点、普通地产效果图感、没有故事的空场景、过度干净的CG感、廉价过饱和、杂乱配景、人物失控、主体建筑被遮挡、过度游戏概念图感、过度插画化、建筑细节丢失。',
  },
};

export const premiumRealEstateStyle: StyleDefinition = {
  id: 'premium_real_estate',
  title: '高端地产感',
  shortDescription: '超真实 / 精致质感 / 温暖叙事',
  coverImage: '/assets/styles/premium_real_estate/cover.webp',
  detailedDescription:
    '高端地产感强调高度真实、精致材质和具有生活温度的建筑可视化表达。它不像北欧氛围感那样偏向冷静、诗意和自然主义氛围，也不像概念戏剧感那样追求戏剧冲击和概念张力，而是更关注高端项目本身的商业完成度、空间品质、材料可信度和生活方式吸引力。\n\n画面应呈现明亮、通透、干净、成熟且昂贵的视觉气质。建筑主体需要被清晰、优雅地展示，体块关系、立面材质、入口界面、景观层次、室内外过渡和公共空间都应具有明确秩序。光线通常自然、柔和、受控，可以是清晨柔光、黄昏暖光、晴朗但不过曝的日光，或精致的室内外灯光，整体应让空间显得真实可信、舒适且有吸引力。\n\n人物、车辆、家具、绿化、水景、灯光和生活配景可以适度出现，用来增强尺度感、生活感和归属感，但不应喧宾夺主。整体效果应接近高端住宅、酒店、商业综合体或品牌地产项目的正式宣传图：画面精修、材质高级、氛围温暖、细节完整，让观者产生对空间品质和生活方式的信任与向往。',
  tags: ['超真实', '精致质感', '温暖叙事', '高端商业', '生活方式', '明亮通透', '高级材质', '可信真实'],
  promptTemplate: {
    styleCore: '高端商业建筑与地产营销导向的建筑可视化表达，强调真实可信、精致完成度、温暖生活方式和成熟高级的项目气质。建筑主体必须清晰、优雅、有吸引力。',
    color: '使用自然、干净、平衡且具有高级感的色彩关系。可采用暖灰、米色、香槟色、自然木色、柔和天空色、低饱和绿植色和精致金属色点缀。整体色彩应温和、通透、现代，避免脏灰、过冷、廉价高饱和或过度滤镜感。',
    lighting: '采用真实、受控且讨好的高端建筑摄影光线，例如清晨柔光、黄昏暖光、晴朗但柔和的日光、精致室内灯光、立面灯光和景观灯光。光线应强化空间品质、材料质感和舒适氛围，避免过度阴郁、强烈戏剧冲突或廉价爆亮效果。',
    atmosphere: '营造成熟、温暖、舒适、可信赖且具有向往感的空间氛围。画面应具有高端生活方式吸引力和商业传播价值，但不能显得浮夸、廉价、过度广告化或虚假。',
    architectureEnvironment: '建筑应与高品质环境自然结合，包括景观、入口界面、街道、泳池、会所、露台、阳台、室内外过渡空间和公共活动区域。环境应服务项目价值表达，让空间看起来真实可达、成熟完整、具有场所感。',
    composition: '使用稳定、清晰、优雅且商业完成度高的构图。突出建筑体量、立面秩序、入口仪式感、景观界面和空间价值。构图应接近高端地产摄影、酒店宣传图或开发商正式发布图，避免过分实验性、过度倾斜透视或主体不明确。',
    material: '强调高品质材料细节和可信质感，例如玻璃、石材、金属、木饰面、幕墙、软装、干净铺装、水面、绿植和精致景观材质。材质应真实、干净、细腻、精修，避免塑料感、粗糙未完成感、过度锐化和廉价反光。',
    entourage: '人物、车辆、家具、灯光、绿化和生活配景可以适度使用，用来传达尺度、活力、服务感和高端生活方式。人物应自然、体面、数量适中，动作和服装应符合高端项目气质，不能遮挡建筑主体或造成杂乱。',
    avoid: '避免过度阴郁、过度概念化、强戏剧冲突、脏乱环境、廉价饱和色、过度HDR、过强锐化、塑料CG感、空洞无生活感、人物过多、建筑主体不清晰、过度浮夸的奢华感、销售图缺乏可信度。',
  },
};

export const painterlyExpressionStyle: StyleDefinition = {
  id: 'painterly_expression',
  title: '绘画感表现',
  shortDescription: '绘画质感 / 艺术表达 / 诗意优雅',
  coverImage: '/assets/styles/painterly_expression/cover.webp',
  detailedDescription:
    '绘画感表现强调建筑图像的艺术表达、诗意氛围和具有手工气质的视觉诠释。它不追求单纯的照片级真实，而是在真实空间关系和建筑逻辑的基础上，加入更明显的绘画感、后期处理感和图像作品气质，让画面更像一张经过艺术构建的建筑作品，而不是普通写实渲染图。\n\n与北欧氛围感的冷静自然主义、概念戏剧感的戏剧冲击、高端地产感的商业完成度不同，这类视觉偏好更注重优雅、细腻、克制且富有诗意的光影诠释，以及建筑与场所之间更具情感和艺术性的关系。画面通常具有柔和但丰富的层次、统一而精致的色彩、轻微的绘画笔触感或后期加工感，适合文化建筑、竞赛方案、公共建筑和概念性较强的设计表达。\n\n建筑主体必须保持清晰可读，空间关系、体块逻辑和场所氛围应明确呈现。人物、植物、天空、地面、水体和环境元素需要共同服务整体图像气质，允许适度的艺术化柔化和抽象处理，但不能让画面变成纯插画、纯拼贴或失去建筑表达。最终效果应具有绘画质感、设计表达力和视觉统一性，让图像呈现优雅、艺术化、富有辨识度的建筑表现气质。',
  tags: ['绘画感', '艺术表达', '诗意光影', '优雅氛围', '竞赛气质', '后期加工感', '细腻质感', '设计导向'],
  promptTemplate: {
    styleCore: '艺术化、绘画感导向的建筑可视化表达，强调设计概念、图像气质、诗意叙事和竞赛表现感，而不是单纯的照片级写实。建筑主体必须保持清晰、优雅和可读。',
    color: '使用统一、克制且具有艺术感的色彩关系，可采用柔和灰调、米色、土色、暖白、低饱和绿植色、粉灰色或精致的暖冷平衡。整体色彩应丰富但和谐，避免廉价高饱和、脏乱综合色和商业广告式过强滤镜感。',
    lighting: '采用柔和、细腻、富有表现力的光线，可使用漫射光、柔和侧光、轻微逆光、安静的天空光和温和的体积氛围。光线重点服务空间气质、层次和诗意，而不是夸张戏剧冲突或过强物理写实。',
    atmosphere: '营造安静、优雅、诗意、具有艺术感和设计气质的图像氛围。允许轻微颗粒感、纸感、绘画感、拼贴感或柔化处理，让画面更接近建筑竞赛图、艺术化表现图和具有作者气质的建筑图像。',
    architectureEnvironment: '建筑应清晰呈现，并与地形、植物、街道、天空、水体、人物和场地环境形成统一的图像表达。环境不只是陪衬，而应共同参与塑造完整的场所感和设计叙事。',
    composition: '使用清晰、稳定、优雅、具有版面感和图像秩序的构图，强调建筑主体、空间层次和设计逻辑。构图应具有艺术作品感和竞赛表达气质，避免过于普通的销售图视角或过度戏剧海报式构图。',
    material: '材质表现应建立在真实基础上，但允许适度柔化、统一和艺术处理。表面应细腻、温和、具有触感和图像质感，避免过强锐化、塑料感、廉价反光、粗糙未完成感和纯CG表面。',
    entourage: '人物、植物、车辆和环境元素应克制、统一并具有图像感，用来增强尺度、氛围和叙事，但不应显得零碎杂乱或喧宾夺主。人物应自然、安静、适度，服务整体艺术叙事。',
    avoid: '避免强烈商业销售图感、过度HDR、过强锐化、廉价高饱和、纯冷硬照片级CG感、塑料材质、过度戏剧化舞台光、杂乱拼贴、完全插画化、建筑主体不清晰、缺乏设计表达和图像统一性。',
  },
};

export const styleDefinitions: StyleDefinition[] = [
  nordicAtmosphereStyle,
  conceptualDramaStyle,
  premiumRealEstateStyle,
  painterlyExpressionStyle,
];

export const STYLE_PRESETS = styleDefinitions;

const STYLE_PRESET_BY_ID = new Map(styleDefinitions.map((style) => [style.id, style]));
const LEGACY_STYLE_ID_MAP: Record<string, string> = {
  mir: 'nordic_atmosphere',
  mir_atmosphere: 'nordic_atmosphere',
  luxigon: 'conceptual_drama',
  luxigon_drama: 'conceptual_drama',
  binyan: 'premium_real_estate',
  binyan_estate: 'premium_real_estate',
};

export function getStylePresetById(id: string | null | undefined) {
  if (!id) return null;
  return STYLE_PRESET_BY_ID.get(id) || STYLE_PRESET_BY_ID.get(LEGACY_STYLE_ID_MAP[id]) || null;
}
