import type { PresetItem, StyleDefinition } from '../types/imageNode.types';
import { getUserPresetById } from '../utils/userPresets';

export const PRESET_TABS = ['我的常用', '变真实', '变时段', '变天气', '变季节'] as const;

export const MAX_MULTI_PRESETS_BY_GROUP: Partial<Record<PresetItem['group'], number>> = {
  accent_style: 2,
  detail_realism: 2,
};

export const PRESET_DATA: PresetItem[] = [
  // ── 变真实 ──
  {
    id: 'photo_realistic',
    name: '照片般真实',
    title: '照片般真实',
    tabs: ['变真实'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '真实光影 / 材质细节',
    description: '真实光影 / 材质细节',
    shortHelp: '提升整体真实度，让画面更接近真实建筑摄影或高质量建筑可视化成片。',
    detailDescription:
      '整体会提升画面的真实度，使结果更接近真实建筑摄影或高质量建筑可视化成片。系统会优先增强自然光影、真实材质、曝光关系、反射细节和建筑表皮质感，同时尽量保留原有建筑主体、构图和主要设计特征。画面不应表现得过度梦幻、过度锐利或明显 AI 化，而应呈现更克制、更可信、更适合展示与汇报的真实效果。',
    keywords: ['真实光影', '自然曝光', '材质细节', '建筑摄影感', '降低 AI 感'],
    promptTemplate: {
      goal: '将当前建筑画面提升为照片级真实效果，尽量保留原图主体、构图、比例关系和关键设计细节。',
      style: '真实摄影感、自然材质、克制高级，不夸张、不梦幻，接近高质量建筑摄影或专业建筑可视化成片。',
      image: '保持建筑主体识别度，不改变主要元素、体块关系和构图逻辑，尽量维持原有方案表达。',
      lighting: '使用自然、可信的光照关系，增强体块明暗层次、投影、环境遮蔽和空间立体感，避免不合理强光和假阴影。',
      color: '保持真实相机感的色彩关系，不过度饱和，不过度滤镜化，整体偏自然中性，符合真实场景。',
      background: '让天空、地面、道路、植物和周边环境保持干净统一，服务主体建筑，不制造杂乱干扰。',
      material: '提升玻璃、金属、石材、混凝土、木材等材质的纹理、反射、粗糙度和细节层次，增强边缘与阴影过渡的真实度。',
      output: '输出为写实摄影感 / 高质量建筑可视化成片效果，适合高清展示与项目表达。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要过度艺术化，不要加入不必要的新元素，不要让画面变成插画、CG 过度渲染或梦幻风格。',
    },
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['照片', '真实', '写实'],
    thumbnail: '/assets/presets/realism/photo-realistic.jpg',
  },
  {
    id: 'artistic_realism',
    name: '艺术化处理',
    title: '艺术化处理',
    tabs: ['变真实'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '克制艺术感 / 高级表达',
    description: '克制艺术感 / 高级表达',
    shortHelp: '在保留建筑主体和构图的基础上，增强画面的艺术表现、空间情绪和视觉完成度。',
    detailDescription:
      '整体会让画面在真实基础上更具艺术化表达，而不是单纯追求照片复刻。系统会强化光影层次、色彩控制、空间氛围、画面留白和建筑与环境之间的关系，让结果更适合概念表达、方案展示和高级建筑视觉呈现。画面应保持克制、自然、有审美，不应变成插画、梦幻图或过度风格化效果。',
    keywords: ['克制艺术感', '空间情绪', '高级表达', '柔和光影', '建筑与环境融合'],
    promptTemplate: {
      goal: '将当前建筑画面提升为具有艺术化表达的高质量建筑可视化效果，在保留建筑主体、构图、比例关系和关键设计细节的基础上，增强空间情绪、画面层次和视觉完成度。',
      style: '克制、高级、艺术化但仍保持真实基础，不追求纯摄影复刻，也不走夸张插画风；整体接近建筑竞赛表现、概念建筑摄影或高审美建筑可视化图像。',
      image: '保持建筑主体识别度、体块关系、立面逻辑和主要构图不变，让建筑与环境、植物、天空、人物活动和场地氛围更加自然融合。',
      lighting: '使用柔和、有层次的自然光或环境光，增强空间纵深、空气感、阴影过渡和建筑体块的情绪表达，避免生硬强光和过度戏剧化光效。',
      color: '色彩应更克制、更统一，可适度低饱和或带有高级灰倾向，避免过度鲜艳、过度商业化和明显滤镜感，使画面具有更强的审美控制。',
      background: '背景、天空、地面、植物和周边环境应服务整体空间叙事，保持干净、有呼吸感，不制造杂乱元素，也不让背景抢占建筑主体。',
      material: '材质表现应真实但不必过度锐利，玻璃、金属、石材、混凝土、木材等材质需要保留触感和层次，同时与整体艺术化氛围协调。',
      output: '输出为具有艺术化建筑表达、高级空间情绪和专业完成度的建筑可视化成片，适合方案展示、概念表达、竞赛图和高审美视觉呈现。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要把画面变成插画、水彩、漫画、奇幻或过度梦幻风格，不要过度添加新元素，不要让艺术化处理破坏建筑方案的清晰表达。',
    },
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['艺术化', '高级表达', '空间情绪'],
    thumbnail: '/assets/presets/realism/artistic-realism.jpg',
  },
  {
    id: 'cinematic_narrative',
    name: '电影感叙事',
    title: '电影感叙事',
    tabs: ['变真实'],
    category: 'realism',
    owner: 'system',
    group: 'realism_mode',
    selectType: 'single',
    selectionMode: 'single',
    exclusiveGroup: 'realism_output_mode',
    shortDescription: '电影光影 / 情绪叙事',
    description: '电影光影 / 情绪叙事',
    shortHelp: '增强电影化光影、冷暖关系、空间故事感和画面情绪，让建筑图更有叙事张力。',
    detailDescription:
      '整体会让画面更具电影感和叙事性。系统会强化光影方向、明暗层次、冷暖对比、前中后景关系和人物活动带来的场景故事感。建筑仍然是主体，但画面不只是展示建筑，而是呈现一种时间、情绪和空间事件。结果应更有镜头感、氛围张力和视觉记忆点，同时避免变成过度戏剧化或虚假的电影海报。',
    keywords: ['电影光影', '冷暖对比', '空间叙事', '情绪氛围', '镜头感'],
    promptTemplate: {
      goal: '将当前建筑画面提升为具有电影感叙事的建筑可视化效果，在保留建筑主体、构图和关键设计细节的基础上，增强画面的情绪、镜头感、空间故事性和视觉张力。',
      style: '电影化、真实、克制、有叙事感，强调光影方向、冷暖关系、空间层次和画面情绪，不做夸张商业海报感或过度特效化处理。',
      image: '保持建筑主体识别度、体块关系、立面逻辑和主要构图不变，通过前景、中景、背景、人物活动和环境元素增强空间叙事，而不是重写建筑方案。',
      lighting: '强化具有方向性的电影光影，可使用侧光、逆光、窗口光、室内暖光或环境冷光来塑造层次，但光线必须符合场景逻辑，避免虚假强光和不合理阴影。',
      color: '色彩可强调冷暖对比、低饱和电影色调或克制的情绪色彩，整体应统一、有氛围、有记忆点，避免过度滤镜、过度青橙或不真实色偏。',
      background: '背景、天空、街道、植物、人物和周边环境应共同服务空间叙事，营造时间感和场景事件感，但不能变得杂乱或抢走建筑主体。',
      material: '材质应在电影化光影下保持真实可读，玻璃、金属、石材、混凝土、地面和水面可体现光线反射与环境反馈，但不要为了戏剧性而牺牲材质可信度。',
      output: '输出为具有电影镜头感、空间叙事、情绪张力和高质量建筑可视化完成度的成片效果，适合建筑宣传、概念表达、故事化场景和高级展示。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要让人物或环境事件压过建筑主体，不要过度添加戏剧化元素，不要变成电影海报、科幻场景、奇幻场景或强特效画面。',
    },
    recommendedInCommon: false,
    userFavorite: false,
    tags: ['电影感', '叙事', '光影'],
    thumbnail: '/assets/presets/realism/cinematic-narrative.jpg',
  },

  // ── 变时段 ──
  {
    id: 'time_early_morning',
    name: '清晨',
    title: '清晨',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '柔和晨光 / 空气感',
    description: '柔和晨光 / 空气感',
    shortHelp: '将画面调整为柔和清晨氛围，强调晨光、空气感和安静的空间情绪。',
    detailDescription:
      '画面会转向清晨时段，呈现柔和晨光、清晰空气感与安静氛围。系统会增强低角度柔光、轻微空气透视和清晨特有的平静情绪，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['柔和晨光', '空气感', '安静氛围', '低角度柔光', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为清晨氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体安静、清新、克制，带有清晨刚开始的柔和空气感。',
      sky: '天空以浅蓝、淡金或微暖的晨光渐变为主，可有轻微薄雾和柔和云层。',
      lighting: '使用低角度、柔和的晨光，阴影轻柔不过重，避免强烈正午光感。',
      color: '整体色彩偏清新、低饱和、柔和冷暖平衡，避免过度金黄或浓烈日落感。',
      environment: '场地、道路、植物和背景应保持安静干净，可表现轻微露水感或清晨空气湿度。',
      materialImpact: '建筑材质受到柔和晨光影响，玻璃和金属可有轻微暖色反射，但保持真实克制。',
      output: '输出为真实可信的清晨建筑可视化氛围图。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成黄昏或日落，不要加入无关元素。',
    },
    recommendedInCommon: true,
    tags: ['清晨', '晨光', '清新'],
    thumbnail: '/assets/presets/time/time-early-morning.jpg',
  },
  {
    id: 'time_morning',
    name: '上午',
    title: '上午',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '干净日光 / 自然通透',
    description: '干净日光 / 自然通透',
    shortHelp: '将画面调整为上午干净日光状态，强调清晰立面、通透空气和自然光线。',
    detailDescription:
      '画面会转向上午时段，呈现干净日光、清晰立面和自然通透的画面状态。系统会增强建筑立面的可读性、自然光照和通透天空，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['干净日光', '清晰立面', '自然通透', '上午光线', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为上午的干净日光氛围，保留建筑主体、构图和设计细节。',
      atmosphere: '整体明亮、清晰、自然通透，适合展示建筑立面和空间关系。',
      sky: '天空以清澈蓝天和少量白云为主，空气可见度高，不要明显日出或日落效果。',
      lighting: '使用自然、干净、方向明确但不过分强烈的上午日光，保证建筑细节清晰可读。',
      color: '整体色彩自然清爽，蓝天、绿植和建筑材质保持真实关系，不要过度饱和。',
      environment: '场地、道路、植物和背景保持干净整洁，减少杂乱干扰，增强通透感。',
      materialImpact: '材质表现应清晰自然，玻璃反射天空，石材、金属、混凝土等保持真实质感。',
      output: '输出为真实可信、明亮通透的上午建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要加入明显清晨薄雾、黄昏暖光或夜景灯光。',
    },
    recommendedInCommon: true,
    tags: ['上午', '日光', '通透'],
    thumbnail: '/assets/presets/time/time-morning.jpg',
  },
  {
    id: 'time_afternoon',
    name: '午后',
    title: '午后',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '温暖日光 / 生活感',
    description: '温暖日光 / 生活感',
    shortHelp: '将画面调整为温暖舒展的午后氛围，强调日光、阴影和生活感。',
    detailDescription:
      '画面会转向午后时段，呈现温暖日光、舒展阴影与更具生活感的环境氛围。系统会增强柔和偏暖的日光、舒展的投影关系和轻松自然的场景情绪，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['温暖日光', '舒展阴影', '生活感', '午后氛围', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为温暖午后氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体舒展、温暖、放松，带有轻微生活感和日常真实感。',
      sky: '天空保持明亮自然，可有柔和云层，不要出现明显日落或夜景效果。',
      lighting: '使用温暖但可信的午后日光，阴影比上午更舒展，增强空间层次和建筑体块感。',
      color: '整体色彩略偏暖，保持自然真实，不要过度金黄或滤镜化。',
      environment: '植物、道路、地面和背景应呈现舒适的日常状态，保持干净统一。',
      materialImpact: '建筑材质在午后暖光下呈现更柔和的高光和阴影，增强真实空间感。',
      output: '输出为真实可信、温暖舒展的午后建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成黄昏、日落或电影化夜景。',
    },
    recommendedInCommon: true,
    tags: ['午后', '温暖', '生活感'],
    thumbnail: '/assets/presets/time/time-afternoon.jpg',
  },
  {
    id: 'time_dusk',
    name: '黄昏',
    title: '黄昏',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '日落天空 / 归家感',
    description: '日落天空 / 归家感',
    shortHelp: '将画面调整为黄昏日落氛围，强调低角度暖光、天空余晖和归家感。',
    detailDescription:
      '画面会转向黄昏时段，呈现低角度暖光、日落天空和温暖的归家感。系统会增强夕阳侧光、暖色天空渐变和柔和阴影，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['黄昏光线', '低角度暖光', '日落天空', '归家感', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为黄昏氛围，保留建筑主体、构图和关键设计细节。',
      atmosphere: '整体温暖、有情绪、有归家感，带有日落前后的柔和情绪。',
      sky: '天空可出现橙金色、粉橙色或暖色日落云层，地平线具有明显余晖。',
      lighting: '使用低角度暖色日落光，增强建筑立面高光、长阴影和体块层次。',
      color: '整体色调偏暖但保持真实，避免过度饱和、梦幻化或插画化。',
      environment: '场地、植物和周边环境应与黄昏光线统一，可适度增强暖光氛围。',
      materialImpact: '玻璃、金属和石材可反射暖色天空，材质受低角度暖光影响但不改变材质类型。',
      output: '输出为真实可信、有归家感的黄昏建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成蓝调或完整夜景，不要加入夸张梦幻天空。',
    },
    recommendedInCommon: true,
    tags: ['黄昏', '日落', '暖光', '归家感'],
    thumbnail: '/assets/presets/time/time-dusk.jpg',
  },
  {
    id: 'time_blue_hour',
    name: '蓝调',
    title: '蓝调',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '冷蓝天空 / 暖光对比',
    description: '冷蓝天空 / 暖光对比',
    shortHelp: '将画面调整为日落后天未全黑的蓝调时刻，强调冷蓝天空与室内暖光的对比。',
    detailDescription:
      '画面会转向蓝调时刻，处于日落后天未全黑的状态，呈现冷蓝天空与室内暖光的冷暖对比。系统会增强深蓝天空、室内灯光外溢和建筑立面的温暖层次，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['蓝调时刻', '冷蓝天空', '室内暖光', '冷暖对比', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为蓝调时刻的建筑氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '日落后天色未完全变黑，整体安静、冷静、高级，具有明显蓝调氛围。',
      sky: '天空呈深冷蓝色，地平线可保留少量余晖，但不要出现明显日落太阳。',
      lighting: '强调冷暖对比，外部环境以冷蓝天光为主，室内窗光、入口灯光和景观灯呈温暖色。',
      color: '整体色调以冷蓝为主，辅以克制暖光点缀，避免过度饱和或赛博朋克化。',
      environment: '保持场地、道路、植物和背景干净统一，可适当增强灯光反射和傍晚空气感。',
      materialImpact: '让玻璃反射蓝调天空，金属、石材和地面材质受到冷暖光影响，但不要改变原有材质类型。',
      output: '输出为真实可信的蓝调建筑可视化氛围图。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成完整夜景，不要出现夸张霓虹、赛博朋克或过度电影化效果。',
    },
    recommendedInCommon: true,
    tags: ['蓝调', '冷蓝', '暖光', '冷暖对比'],
    thumbnail: '/assets/presets/time/time-blue-hour.jpg',
  },
  {
    id: 'time_night',
    name: '夜景',
    title: '夜景',
    tabs: ['变时段'],
    category: 'atmosphere',
    group: 'time',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '夜间灯光 / 安静高级',
    description: '夜间灯光 / 安静高级',
    shortHelp: '将画面调整为完整夜间状态，主要依靠室内灯光、街灯、景观灯和商业灯光塑造画面。',
    detailDescription:
      '画面会转向完整夜间状态，主要依靠室内灯光、街灯、景观灯和商业灯光塑造画面。系统会增强建筑照明层次、道路与景观灯光、夜间天空和城市环境亮度，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['夜景灯光', '室内灯光', '街灯', '景观灯', '商业灯光'],
    promptTemplate: {
      goal: '将当前建筑画面调整为真实夜景氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '完整夜间状态，整体安静、高级、具有灯光塑造的空间层次。',
      sky: '天空为深蓝或蓝黑色夜空，可有轻微云层或低亮度环境光，不要保留明显日落余晖。',
      lighting: '主要依靠室内灯光、建筑立面灯光、街灯、景观灯和商业灯光塑造画面，灯光应真实可信。',
      color: '整体以深色夜景基调为主，暖光作为视觉重点，冷暖关系克制自然。',
      environment: '道路、植物、水面或地面可出现适度灯光反射，但保持画面干净，不要杂乱。',
      materialImpact: '玻璃应呈现夜间反射和室内透光，金属、石材和地面材质受到灯光影响形成真实高光。',
      output: '输出为真实可信、灯光层次明确的夜景建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成赛博朋克、霓虹街景或过度夸张商业灯光。',
    },
    recommendedInCommon: true,
    tags: ['夜景', '灯光', '商业氛围'],
    thumbnail: '/assets/presets/time/time-night.jpg',
  },

  // ── 变天气 ──
  {
    id: 'weather_sunny',
    name: '晴天',
    title: '晴天',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '明亮日光 / 通透清晰',
    description: '明亮日光 / 通透清晰',
    shortHelp: '将画面调整为晴朗天气，强调清晰蓝天、明亮日光和高可见度。',
    detailDescription:
      '画面会调整为晴天天气，呈现明亮日光、通透清晰、高可见度和干净蓝天。系统会增强清爽自然光、清晰对比和透明空气感，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['明亮日光', '通透清晰', '高可见度', '干净蓝天', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为晴朗天气状态，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体明亮、通透、清爽，具有高可见度和干净天气感。',
      sky: '天空清澈蓝色，可有少量柔和白云，不要出现阴沉厚云或雾霾。',
      lighting: '自然晴天日光，明暗关系清晰，投影可信但不过分生硬。',
      color: '整体色彩清爽自然，蓝天和绿植适度鲜明但不过度饱和。',
      environment: '场地、道路、植物和背景保持干净清晰，远景可见度高。',
      materialImpact: '玻璃反射蓝天，材质高光和阴影自然清晰。',
      output: '输出为真实可信、清晰通透的晴天建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成强烈 HDR 或过度饱和广告风。',
    },
    recommendedInCommon: true,
    tags: ['晴天', '日光', '蓝天'],
    thumbnail: '/assets/presets/weather/weather-sunny.jpg',
  },
  {
    id: 'weather_cloudy',
    name: '多云',
    title: '多云',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '层次云影 / 柔和日光',
    description: '层次云影 / 柔和日光',
    shortHelp: '将画面调整为多云天气，强调云层变化、柔和日光和平衡对比。',
    detailDescription:
      '画面会调整为多云天气，呈现层次云影、柔和日光、云层变化和自然平衡的环境状态。系统会增强浅灰与白色云层的层次、柔和云影和稳定对比，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['层次云影', '柔和日光', '云层变化', '自然平衡', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为多云天气状态，保留建筑主体、构图和设计细节。',
      atmosphere: '整体自然、平衡、柔和，有云层变化但不阴沉。',
      sky: '天空包含蓝天、白云和浅灰云层，云层有层次但仍有部分蓝天可见。',
      lighting: '使用柔和漫射日光，保留轻微云影变化，降低过强直射光。',
      color: '整体色彩自然平衡，明度适中，对比不过强也不过低。',
      environment: '场地、道路、植物和背景保持自然清晰，云影可带来轻微变化。',
      materialImpact: '建筑材质在柔和日光下保持细节可读，玻璃反射云层和天空。',
      output: '输出为真实可信、柔和自然的多云建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成阴天、雨天或厚重风暴云。',
    },
    recommendedInCommon: true,
    tags: ['多云', '云影', '柔和'],
    thumbnail: '/assets/presets/weather/weather-cloudy.jpg',
  },
  {
    id: 'weather_overcast',
    name: '阴天',
    title: '阴天',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '灰云漫射 / 低对比',
    description: '灰云漫射 / 低对比',
    shortHelp: '将画面调整为阴天状态，强调灰云漫射光、低对比和安静克制的氛围。',
    detailDescription:
      '画面会调整为阴天天气，呈现灰云漫射、低对比、无直射光和安静克制的低饱和氛围。系统会消除硬边阴影，增强均匀柔光和克制色调，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['灰云漫射', '低对比', '无直射光', '安静克制', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为阴天氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体安静、克制、低对比，带有灰云覆盖下的柔和感。',
      sky: '天空被连续灰云覆盖，没有明显蓝天和直射太阳。',
      lighting: '使用均匀漫射光，减少强烈投影和高光，保持建筑体块关系可读。',
      color: '整体色彩偏低饱和、中性偏冷，避免过暗或沉闷失真。',
      environment: '场地、植物和背景保持安静统一，减少强烈明暗变化。',
      materialImpact: '材质高光变弱，玻璃反射灰云天空，石材和混凝土表现更柔和。',
      output: '输出为真实可信、低对比但仍清晰的阴天建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成雾天、雨天或夜景。',
    },
    recommendedInCommon: true,
    tags: ['阴天', '灰云', '低对比'],
    thumbnail: '/assets/presets/weather/weather-overcast.jpg',
  },
  {
    id: 'weather_after_rain',
    name: '雨后',
    title: '雨后',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '湿润反光 / 清新空气',
    description: '湿润反光 / 清新空气',
    shortHelp: '将画面调整为雨后状态，强调湿润地面、清新空气、反光和饱和绿植。',
    detailDescription:
      '画面会调整为雨后状态，呈现湿润反光、清新空气、饱和绿植和雨后恢复感。系统会增强地面或铺装的细微反射、潮湿空气、绿植饱和度和云层散开后的柔和光线，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['湿润反光', '清新空气', '饱和绿植', '雨后恢复感', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为雨后氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体清新、湿润、安静，像降雨刚结束后的恢复感。',
      sky: '天空可有破开的云层、柔和天光或局部放晴，不要表现为正在暴雨。',
      lighting: '使用雨后柔和光线，可有轻微反射高光和湿润空气中的漫射感。',
      color: '绿植和地面色彩略更饱和，整体保持真实清新，不要过度滤镜化。',
      environment: '地面、道路、铺装和草地可表现湿润状态，可有少量水洼和反光。',
      materialImpact: '玻璃、石材、金属、铺装和地面应呈现湿润反光，增强真实雨后质感。',
      output: '输出为真实可信、湿润清新的雨后建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成正在下大雨、洪水或戏剧化暴风天气。',
    },
    recommendedInCommon: true,
    tags: ['雨后', '湿润', '反光'],
    thumbnail: '/assets/presets/weather/weather-after-rain.jpg',
  },
  {
    id: 'weather_foggy',
    name: '雾天',
    title: '雾天',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '朦胧雾气 / 空气纵深',
    description: '朦胧雾气 / 空气纵深',
    shortHelp: '将画面调整为雾天状态，强调空气透视、低对比、远景朦胧和诗意安静。',
    detailDescription:
      '画面会调整为雾天天气，呈现朦胧雾气、空气纵深、低对比和诗意安静的氛围。系统会让远景元素被薄雾部分遮挡，增强柔和漫射光和空间层次，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['朦胧雾气', '空气纵深', '低对比', '诗意安静', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为雾天氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体安静、朦胧、柔和，具有明显空气纵深和低对比氛围。',
      sky: '天空偏浅灰、灰蓝或被雾气柔化，没有强烈太阳和高对比云层。',
      lighting: '使用柔和漫射光，降低远景对比，让空间层次通过雾气逐渐递减。',
      color: '整体色彩低饱和、偏冷或中性，保持诗意但不要脏灰。',
      environment: '远处建筑、树木和背景可被雾气部分遮挡，近景主体仍需清晰可读。',
      materialImpact: '材质高光和反射被空气雾化柔化，边缘对比降低但不丢失主体。',
      output: '输出为真实可信、具有空气纵深和安静氛围的雾天建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要让雾气完全遮挡主体，不要变成阴天或雨天。',
    },
    recommendedInCommon: true,
    tags: ['雾天', '朦胧', '诗意'],
    thumbnail: '/assets/presets/weather/weather-foggy.jpg',
  },
  {
    id: 'weather_snow',
    name: '雪景',
    title: '雪景',
    tabs: ['变天气'],
    category: 'atmosphere',
    group: 'weather',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '积雪氛围 / 清冷安静',
    description: '积雪氛围 / 清冷安静',
    shortHelp: '将画面调整为雪景状态，强调积雪、冷空气感和安静清冷的建筑氛围。',
    detailDescription:
      '画面会调整为雪景天气，呈现积雪氛围、清冷安静、冷空气感以及雪后或轻微飘雪效果。系统会增强地面、屋顶边缘和景观局部积雪、柔和漫射光和安静清冷的环境情绪，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['积雪氛围', '清冷安静', '冷空气感', '轻微飘雪', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为雪景氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体清冷、安静、低对比，具有雪后或轻微飘雪的冬日氛围。',
      sky: '天空可为冷淡蓝色、浅灰色或柔和冬季云层，不要出现强烈艳丽天空。',
      lighting: '使用柔和漫射冷光，避免过强直射光，让雪面和建筑形成真实层次。',
      color: '整体色彩偏冷、低饱和，白色积雪保持细节，不要过曝成纯白。',
      environment: '地面、屋顶边缘、植物、景观和道路可出现积雪或薄雪覆盖，保持干净真实。',
      materialImpact: '玻璃、金属、石材和地面材质受到冷光与雪面反射影响，表现清冷但可信。',
      output: '输出为真实可信、清冷安静的雪景建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要变成暴雪灾害，不要让积雪完全淹没建筑细节。',
    },
    recommendedInCommon: true,
    tags: ['雪景', '积雪', '清冷'],
    thumbnail: '/assets/presets/weather/weather-snow.jpg',
  },

  // ── 变季节 ──
  {
    id: 'season_spring',
    name: '春季',
    title: '春季',
    tabs: ['变季节'],
    category: 'atmosphere',
    group: 'season',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '嫩叶新绿 / 清新生机',
    description: '嫩叶新绿 / 清新生机',
    shortHelp: '将画面调整为春季状态，强调新绿、嫩叶、轻盈空气和生机感。',
    detailDescription:
      '画面会呈现春季环境，嫩叶新绿、柔和日光、清新草地和轻微花意共同营造清新生机。系统会增强春季自然变化和轻盈空气感，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['嫩叶新绿', '清新生机', '柔和日光', '春季变化', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为春季氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体清新、轻盈、有生机，呈现春天刚展开的自然状态。',
      sky: '天空可为柔和蓝天或轻云，光线干净不过强烈。',
      lighting: '使用柔和自然日光，增强春季清新感和空气感。',
      color: '整体色彩以浅绿、嫩绿和柔和自然色为主，避免过度鲜艳。',
      environment: '场地、草地和景观呈现新生状态，可有少量花朵或嫩芽，但不要杂乱。',
      vegetation: '树木和植物应表现嫩叶、新绿、轻微花开或春季生长感。',
      materialImpact: '建筑材质保持真实，受柔和春光影响呈现清新干净的质感。',
      output: '输出为真实可信、清新有生机的春季建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要让花朵过多抢占主体，不要变成童话或插画风。',
    },
    recommendedInCommon: true,
    tags: ['春季', '嫩叶', '清新'],
    thumbnail: '/assets/presets/season/season-spring.jpg',
  },
  {
    id: 'season_summer',
    name: '夏季',
    title: '夏季',
    tabs: ['变季节'],
    category: 'atmosphere',
    group: 'season',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '繁茂绿意 / 明亮饱满',
    description: '繁茂绿意 / 明亮饱满',
    shortHelp: '将画面调整为夏季状态，强调浓绿植被、明亮日光和饱满生命力。',
    detailDescription:
      '画面会呈现夏季环境，繁茂深绿的树冠、明亮清晰的日光、丰富草地和充满活力的自然氛围共同塑造明亮饱满的季节感，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['繁茂绿意', '明亮饱满', '深绿树冠', '夏季活力', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为夏季氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体明亮、饱满、自然，具有夏季绿意和生命力。',
      sky: '天空可为明亮蓝天或少量白云，天气清晰通透。',
      lighting: '使用明亮自然日光，可有较清晰阴影，但避免过曝和刺眼。',
      color: '整体色彩以饱满绿植、自然蓝天和真实建筑材质为主，避免过度饱和。',
      environment: '场地和景观呈现夏季繁茂状态，草地、灌木和树木更丰盛。',
      vegetation: '树冠饱满、叶片浓密、草地鲜绿，体现夏季旺盛生长状态。',
      materialImpact: '建筑材质在明亮日光下保持清晰真实，高光和阴影自然。',
      output: '输出为真实可信、明亮饱满的夏季建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要让绿植过度遮挡建筑，不要变成热带幻想场景。',
    },
    recommendedInCommon: true,
    tags: ['夏季', '繁茂', '明亮'],
    thumbnail: '/assets/presets/season/season-summer.jpg',
  },
  {
    id: 'season_autumn',
    name: '秋季',
    title: '秋季',
    tabs: ['变季节'],
    category: 'atmosphere',
    group: 'season',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '金黄橙叶 / 温暖层次',
    description: '金黄橙叶 / 温暖层次',
    shortHelp: '将画面调整为秋季状态，强调金黄、橙红、成熟温暖和季节层次。',
    detailDescription:
      '画面会呈现秋季环境，金黄橙叶、温暖阳光、略干草地和成熟安静的画面情绪共同形成丰富的季节色彩层次，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['金黄橙叶', '温暖层次', '秋季色彩', '成熟安静', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为秋季氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体成熟、温暖、安静，具有秋季的层次和收敛感。',
      sky: '天空可为柔和蓝天、浅金色光线或轻微秋季薄雾。',
      lighting: '使用柔和偏暖的秋季日光，增强树叶和建筑表面的温暖层次。',
      color: '整体色彩以金黄、橙色、棕色和低饱和暖色为主，保持真实克制。',
      environment: '草地、道路和景观可出现秋季落叶、枯草或暖色植被，但不要杂乱。',
      vegetation: '树木和植物应表现黄色、橙色、红棕色秋叶和季节转换状态。',
      materialImpact: '建筑材质受到暖色秋光影响，呈现柔和成熟的真实质感。',
      output: '输出为真实可信、温暖有层次的秋季建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要让秋叶过度遮挡主体，不要过度滤镜化。',
    },
    recommendedInCommon: true,
    tags: ['秋季', '金黄', '橙叶'],
    thumbnail: '/assets/presets/season/season-autumn.jpg',
  },
  {
    id: 'season_winter',
    name: '冬季',
    title: '冬季',
    tabs: ['变季节'],
    category: 'atmosphere',
    group: 'season',
    selectType: 'single',
    selectionMode: 'single',
    shortDescription: '裸枝霜感 / 清冷安静',
    description: '裸枝霜感 / 清冷安静',
    shortHelp: '将画面调整为冬季状态，强调裸枝、低饱和、冷空气和轻霜感，但不默认变成雪景。',
    detailDescription:
      '画面会呈现冬季环境，裸枝、清冷浅光、霜感草地和低饱和景观共同营造克制安静的季节氛围。冬季不等于完整雪景，只表现冷空气、裸枝、低饱和和轻霜感，同时保持建筑主体、构图和主要设计特征不变。',
    keywords: ['裸枝霜感', '清冷安静', '低饱和景观', '轻霜感', '建筑氛围'],
    promptTemplate: {
      goal: '将当前建筑画面调整为冬季氛围，保留建筑主体、构图和主要设计关系。',
      atmosphere: '整体清冷、安静、克制，具有冬季低温感和低饱和状态。',
      sky: '天空可为冷淡蓝色、浅灰色或柔和冬季云层，不要强烈艳丽。',
      lighting: '使用低角度或柔和冷日光，增强冬季清冷氛围和空间层次。',
      color: '整体色彩低饱和、偏冷，减少鲜艳绿植和暖色过度表现。',
      environment: '场地、草地和背景可呈现枯草、轻霜、湿冷地面或冬季干净状态，但不要默认大面积积雪。',
      vegetation: '树木以裸枝、少叶、低饱和冬季植被为主，体现休眠状态。',
      materialImpact: '建筑材质在冷光下呈现更克制的反射和阴影，保持真实清冷质感。',
      output: '输出为真实可信、清冷安静的冬季建筑可视化画面。',
      constraints: '不要改变建筑主体设计，不要改变主要构图，不要默认生成完整雪景；如果用户同时选择雪景，才允许明显积雪。',
    },
    recommendedInCommon: true,
    tags: ['冬季', '裸枝', '清冷'],
    thumbnail: '/assets/presets/season/season-winter.jpg',
  },

  // ── 旧换氛围/换环境/换视角项（保留数据，不在 UI 展示） ──
  {
    id: 'sunset_mood',
    name: '黄昏氛围',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '暖色天空 / 柔和侧光',
    promptTemplate: '将整体画面调整为黄昏氛围，呈现暖色天空、柔和侧光和归家情绪，保持建筑主体结构、相机角度和构图比例不变。',
    tags: ['黄昏', '日落', '暖色', '侧光'],
    thumbnail: '/images/show-cover-7.jpg',
  },
  {
    id: 'morning_mood',
    name: '清晨氛围',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '柔和晨光 / 清新空气',
    promptTemplate: '营造清晨氛围，呈现柔和晨光、清新空气感与明亮温和的情绪，保持建筑主体结构、相机角度和构图比例不变。',
    tags: ['清晨', '晨光', '清新'],
    thumbnail: '/images/show-cover-8.jpg',
  },
  {
    id: 'afternoon_sun',
    name: '午后阳光',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '强烈阳光 / 清晰阴影',
    promptTemplate: '调整为午后阳光氛围，呈现强烈阳光照射、清晰阴影与明亮通透的画面感。',
    tags: ['午后', '阳光', '明亮'],
    thumbnail: '/images/show-cover-9.jpg',
  },
  {
    id: 'night_lighting',
    name: '夜景灯光',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '室内灯光 / 深蓝天空',
    promptTemplate: '转为夜景表现，增强室内灯光与建筑外立面照明效果，优化夜间天空的深蓝调与城市光污染的层次。',
    tags: ['夜景', '灯光', '深蓝'],
    thumbnail: '/images/show-cover-10.jpg',
  },
  {
    id: 'soft_diffused',
    name: '柔和散射光',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '阴天柔光 / 无硬边',
    promptTemplate: '使用柔和散射光处理画面，消除硬边阴影，呈现细腻均匀的光影过渡。',
    tags: ['柔和', '散射', '均匀'],
    thumbnail: '/images/show-cover-11.jpg',
  },
  {
    id: 'grey_mood',
    name: '高级灰氛围',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '低饱和灰调 / 克制情绪',
    promptTemplate: '营造高级灰氛围，降低整体饱和度，使用克制、内敛的色调表达建筑情绪。',
    tags: ['高级灰', '低饱和', '克制'],
    thumbnail: '/images/show-cover-12.jpg',
  },
  {
    id: 'morning_fog',
    name: '清晨雾气',
    tabs: [],
    category: 'mood',
    group: 'main_mood',
    selectType: 'single',
    shortDescription: '薄雾 / 空气透视',
    promptTemplate: '添加柔和的清晨薄雾效果，降低远景对比度，增强空气透视感，使建筑在朦胧晨光中呈现诗意的氛围与层次感。',
    tags: ['雾气', '清晨', '朦胧'],
    thumbnail: '/images/show-cover-13.jpg',
  },
  {
    id: 'sunny',
    name: '晴天',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '晴朗无云',
    promptTemplate: '将环境设为晴朗天气，呈现明亮通透的天空与清晰的光影关系。',
    tags: ['晴天', '晴朗', '明亮'],
    thumbnail: '/images/show-cover-14.jpg',
  },
  {
    id: 'cloudy',
    name: '阴天',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '多云覆盖',
    promptTemplate: '将环境设为阴天，呈现多云覆盖的天空与柔和均匀的光线。',
    tags: ['阴天', '多云', '柔和'],
    thumbnail: '/images/show-cover-15.jpg',
  },
  {
    id: 'after_rain',
    name: '雨后',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '湿润路面 / 反射细节',
    promptTemplate: '呈现雨后环境，湿润路面与反射细节，空气清透，云层富有层次。',
    tags: ['雨后', '湿润', '反射'],
    thumbnail: '/images/show-cover-16.jpg',
  },
  {
    id: 'light_rain_old',
    name: '小雨',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '细雨氛围',
    promptTemplate: '添加小雨氛围，呈现细雨、湿润感与柔和的环境反射。',
    tags: ['小雨', '细雨', '湿润'],
    thumbnail: '/images/show-cover-17.jpg',
  },
  {
    id: 'snow_scene',
    name: '雪景',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '积雪覆盖 / 冬季冷调',
    promptTemplate: '添加积雪覆盖效果，优化雪的质感与厚度分布，增强冬季冷色调氛围。',
    tags: ['雪景', '冬季', '积雪'],
    thumbnail: '/images/show-cover-18.jpg',
  },
  {
    id: 'foggy',
    name: '雾气',
    tabs: [],
    category: 'environment',
    group: 'weather',
    selectType: 'single',
    shortDescription: '浓雾 / 朦胧远景',
    promptTemplate: '添加浓雾效果，营造朦胧远景与神秘氛围，降低远景清晰度。',
    tags: ['雾气', '朦胧', '远景'],
    thumbnail: '/images/show-cover-19.jpg',
  },
  {
    id: 'spring_old',
    name: '春季',
    tabs: [],
    category: 'environment',
    group: 'season',
    selectType: 'single',
    shortDescription: '生机 / 绿意',
    promptTemplate: '呈现春季环境，增强绿意与生机感，优化植物色彩与光线温度。',
    tags: ['春季', '生机', '绿意'],
    thumbnail: '/images/show-cover-20.jpg',
  },
  {
    id: 'summer_old',
    name: '夏季',
    tabs: [],
    category: 'environment',
    group: 'season',
    selectType: 'single',
    shortDescription: '浓绿 / 强烈阳光',
    promptTemplate: '呈现夏季环境，浓绿植被与强烈阳光，增强画面的活力与饱和度。',
    tags: ['夏季', '浓绿', '阳光'],
    thumbnail: '/images/show-cover-1.jpg',
  },
  {
    id: 'autumn_old',
    name: '秋季',
    tabs: [],
    category: 'environment',
    group: 'season',
    selectType: 'single',
    shortDescription: '金黄 / 温暖色调',
    promptTemplate: '呈现秋季环境，金黄植被与温暖色调，优化落叶与光线氛围。',
    tags: ['秋季', '金黄', '温暖'],
    thumbnail: '/images/show-cover-2.jpg',
  },
  {
    id: 'winter_old',
    name: '冬季',
    tabs: [],
    category: 'environment',
    group: 'season',
    selectType: 'single',
    shortDescription: '萧瑟 / 冷色调',
    promptTemplate: '呈现冬季环境，萧瑟景观与冷色调，优化枯枝与清冷光线。',
    tags: ['冬季', '萧瑟', '冷调'],
    thumbnail: '/images/show-cover-3.jpg',
  },
  {
    id: 'human_eye',
    name: '人视角',
    tabs: [],
    category: 'perspective',
    group: 'perspective',
    selectType: 'single',
    shortDescription: '1.6m 眼高 / 自然透视',
    promptTemplate: '调整为人视角（约1.6m眼高），呈现自然的人体透视与尺度感，尽量保持建筑主体设计、体量关系、材质逻辑和设计语言一致。',
    tags: ['人视角', '眼高', '自然'],
    thumbnail: '/images/show-cover-4.jpg',
  },
  {
    id: 'street_view',
    name: '街景视角',
    tabs: [],
    category: 'perspective',
    group: 'perspective',
    selectType: 'single',
    shortDescription: '街道水平视角',
    promptTemplate: '调整为街景视角，呈现街道水平观察角度与城市环境关系，尽量保持建筑主体设计、体量关系、材质逻辑和设计语言一致。',
    tags: ['街景', '街道', '水平'],
    thumbnail: '/images/show-cover-5.jpg',
  },
  {
    id: 'entrance_closeup',
    name: '入口特写',
    tabs: [],
    category: 'perspective',
    group: 'perspective',
    selectType: 'single',
    shortDescription: '入口区域聚焦',
    promptTemplate: '调整为入口特写视角，聚焦建筑入口区域的空间细节与材质表现，尽量保持建筑主体设计、体量关系、材质逻辑和设计语言一致。',
    tags: ['入口', '特写', '聚焦'],
    thumbnail: '/images/show-cover-6.jpg',
  },
  {
    id: 'drone_view',
    name: '无人机视角',
    tabs: [],
    category: 'perspective',
    group: 'perspective',
    selectType: 'single',
    shortDescription: '鸟瞰 / 半鸟瞰',
    promptTemplate: '调整为无人机视角（鸟瞰或半鸟瞰），呈现建筑整体布局与周边环境关系，尽量保持建筑主体设计、体量关系、材质逻辑和设计语言一致。',
    tags: ['无人机', '鸟瞰', '俯瞰'],
    thumbnail: '/images/show-cover-7.jpg',
  },
];

const PRESET_BY_ID = new Map(PRESET_DATA.map((preset) => [preset.id, preset]));

export function getPresetById(id: string) {
  return PRESET_BY_ID.get(id) || getUserPresetById(id);
}

export const mirStyle: StyleDefinition = {
  id: 'mir',
  title: 'MIR 氛围感',
  shortDescription: '低饱和 / 诗意氛围 / 柔和自然光',
  coverImage: '/assets/styles/mir/cover.jpg',
  detailedDescription:
    'MIR 氛围感强调低饱和、冷灰调、柔和自然光和强烈的环境氛围。画面不追求商业效果图式的高清锐利，而是营造一种诗意、冷静、内敛、略带忧郁的建筑图像气质。\n\n建筑应与地形、植物、天空、雾气、雨雪、水体等自然环境深度融合，而不是像单独摆放在场景中的物体。画面通常采用阴天、薄雾、漫射光、侧光、逆光或冬季感光线，避免强烈直射阳光、纯净蓝天和过高饱和度。\n\n整体质感偏向绘画感与自然主义，更接近高级建筑摄影与数字手绘合成之间的状态。材质表现应真实但克制，不夸张、不塑料感、不强 HDR。人物和活动元素应尽量少且处理克制，重点仍然是建筑在环境中的存在感与时间感。',
  tags: ['低饱和', '冷灰调', '阴天漫射光', '薄雾空气感', '绘画感', '建筑融于环境', '冷静叙事', '北欧气质'],
  promptTemplate: {
    styleCore: '高度氛围化的建筑可视化表达，强调北欧自然主义气质、诗意叙事感和柔和绘画感，不追求硬质商业CG效果。',
    color: '使用低饱和、冷灰调、克制的自然色彩关系，避免鲜艳、高饱和和地产广告式配色。',
    lighting: '采用柔和自然光、阴天漫射光、侧光、逆光或雾中光感，避免强烈直射阳光和生硬阴影。',
    atmosphere: '营造安静、冷静、略带忧郁的环境氛围，允许轻微薄雾、空气透视和柔和颗粒感。',
    architectureEnvironment: '强调建筑与自然环境、景观、地形、植物、天空、水体的深度融合，让建筑像已经在场地中存在很久。',
    composition: '保持克制、冷静、电影化的构图，强调空间层次、环境包裹感和建筑摄影式视角。',
    material: '材质真实但柔和，不要过度锐化、过度反光、过强CG塑料感。',
    entourage: '人物和配景元素应克制，数量少，避免喧宾夺主，重点服务建筑与场景氛围。',
    avoid: '避免纯蓝天大晴天、过高饱和、商业地产广告感、塑料CG感、夸张HDR、过强锐化、人物过多、舞台式强打光。',
  },
};

export const luxigonStyle: StyleDefinition = {
  id: 'luxigon',
  title: 'Luxigon 戏剧感',
  shortDescription: '强对比 / 概念叙事 / 戏剧化冲击',
  coverImage: '/assets/styles/luxigon/cover.jpg',
  detailedDescription:
    'Luxigon 戏剧感强调强烈的视觉冲击力、概念叙事和电影化光影。画面不只是展示建筑外观，而是将建筑放入一个具有情绪、事件和故事张力的场景中，让建筑成为画面中的视觉主角和叙事核心。\n\n与 MIR 的冷静、低饱和、自然主义氛围不同，Luxigon 更偏向大胆、外放、艺术化和戏剧化的表达。画面可以使用更强烈的明暗反差、更鲜明的冷暖对比、更有表现力的天空、云层、烟雾、逆光、城市活动或超现实氛围，用来放大设计概念和空间情绪。\n\n这种风格适合让建筑图像更有传播性、记忆点和概念冲击力。人物、车辆、灯光、天气和城市配景可以更积极地参与画面叙事，但必须服务于建筑主体，不能让画面变得混乱或把建筑淹没。最终效果应接近一张高质量的建筑电影海报：有张力、有故事、有视觉中心，同时仍然保持建筑可视化的空间可信度和设计表达清晰度。',
  tags: ['戏剧光影', '强对比', '概念叙事', '电影感', '视觉冲击', '大胆色彩', '城市事件', '海报感'],
  promptTemplate: {
    styleCore: '戏剧化、概念叙事导向的建筑可视化表达，强调强烈视觉冲击、电影化场景、情绪张力和设计概念的视觉放大。建筑必须保持清晰主体地位，而不是被环境元素淹没。',
    color: '使用更大胆、更有表现力的色彩关系，允许强烈冷暖对比、深蓝阴影、橙红天空、霓虹色点缀、浓郁黄昏或夜景色调。色彩可以鲜明但必须高级、受控，避免廉价过饱和和杂乱配色。',
    lighting: '采用强烈戏剧化光影，例如强侧光、逆光、轮廓光、局部聚焦光、夜景灯光、体积光、穿透云层的光束或高反差环境光。光线应强化建筑体量、边缘轮廓、空间深度和画面张力。',
    atmosphere: '营造充满能量、事件感和故事性的画面氛围。可以加入戏剧化天空、厚重云层、烟雾、雨雪、湿润地面、反射、光束、城市活动或轻微超现实元素，让画面具有记忆点和传播感。',
    architectureEnvironment: '建筑应作为视觉故事的核心角色，与城市环境、人群活动、交通、天气、景观、灯光和场地事件形成完整叙事。环境元素可以丰富，但必须围绕建筑展开，不能遮挡或削弱建筑主体。',
    composition: '使用电影化、海报化、具有强视觉中心的构图。允许大胆透视、前景遮挡、强剪影、动态人群、低机位、广角张力和富有冲击力的画面布局，但仍需保持建筑形体、比例和空间关系清晰。',
    material: '材质表现应保持可信，同时可以通过更强的高光、反射、湿润地面、夜景灯光、金属与玻璃反射、局部明暗对比来增强表现力。避免塑料感、廉价CG质感和无细节的大面积假材质。',
    entourage: '人物、车辆、活动、城市配景和环境细节可以比克制风格更积极地出现，用来制造事件感和画面故事。但数量、位置和明暗关系必须受控，不能造成杂乱，也不能抢走建筑主体的注意力。',
    avoid: '避免平淡光照、低对比、灰暗无重点、普通地产效果图感、没有故事的空场景、过度干净的CG感、廉价过饱和、杂乱配景、人物失控、主体建筑被遮挡、过度游戏概念图感、过度插画化、建筑细节丢失。',
  },
};

export const binyanStyle: StyleDefinition = {
  id: 'binyan',
  title: 'Binyan 高级感',
  shortDescription: '超真实 / 精致质感 / 温暖叙事',
  coverImage: '/assets/styles/binyan/cover.jpg',
  detailedDescription:
    'Binyan 高级感强调高度真实、精致材质和具有生活温度的建筑可视化表达。它不像 MIR 那样偏向冷静、诗意和自然主义氛围，也不像 Luxigon 那样追求戏剧冲击和概念张力，而是更关注高端项目本身的商业完成度、空间品质、材料可信度和生活方式吸引力。\n\n画面应呈现明亮、通透、干净、成熟且昂贵的视觉气质。建筑主体需要被清晰、优雅地展示，体块关系、立面材质、入口界面、景观层次、室内外过渡和公共空间都应具有明确秩序。光线通常自然、柔和、受控，可以是清晨柔光、黄昏暖光、晴朗但不过曝的日光，或精致的室内外灯光，整体应让空间显得真实可信、舒适且有吸引力。\n\n人物、车辆、家具、绿化、水景、灯光和生活配景可以适度出现，用来增强尺度感、生活感和归属感，但不应喧宾夺主。整体效果应接近高端住宅、酒店、商业综合体或品牌地产项目的正式宣传图：画面精修、材质高级、氛围温暖、细节完整，让观者产生对空间品质和生活方式的信任与向往。',
  tags: ['超真实', '精致质感', '温暖叙事', '高端商业', '生活方式', '明亮通透', '高级材质', '可信真实'],
  promptTemplate: {
    styleCore: '高端商业建筑与地产营销导向的建筑可视化表达，强调真实可信、精致完成度、温暖生活方式和成熟高级的项目气质。建筑主体必须清晰、优雅、有吸引力。',
    color: '使用自然、干净、平衡且具有高级感的色彩关系。可采用暖灰、米色、香槟色、自然木色、柔和天空色、低饱和绿植色和精致金属色点缀。整体色彩应温和、通透、现代，避免脏灰、过冷、廉价高饱和或过度滤镜感。',
    lighting: '采用真实、受控且讨好的高端建筑摄影光线，例如清晨柔光、黄昏暖光、晴朗但柔和的日光、精致室内灯光、立面灯光和景观灯光。光线应强化空间品质、材料质感和舒适氛围，避免过度阴郁、强烈戏剧冲突或廉价爆亮效果。',
    atmosphere: '营造成熟、温暖、舒适、可信赖且具有向往感的空间氛围。画面应具有高端生活方式吸引力和商业传播价值，但不能显得浮夸、廉价、过度广告化或虚假。',
    architectureEnvironment: '建筑应与高品质环境自然结合，包括景观、入口界面、街道、泳池、会所、露台、阳台、室内外过渡空间和公共活动区域。环境应服务项目价值表达，让空间看起来真实可达、成熟完整、具有场所感。',
    composition: '使用稳定、清晰、优雅且商业完成度高的构图。突出建筑体量、立面秩序、入口仪式感、景观界面和空间价值。构图应接近高端地产摄影、酒店宣传图或开发商正式发布图，避免过分实验性、过度倾斜透视或主体不明确。',
    material: '强调高品质材料细节和可信质感，例如玻璃、石材、金属、木饰面、幕墙、软装、干净铺装、水面、绿植和精致景观材质。材质应真实、干净、细腻、精修，避免塑料感、粗糙未完成感、过度锐化和廉价反光。',
    entourage: '人物、车辆、家具、灯光、绿化和生活配景可以适度使用，用来传达尺度、活力、服务感和高端生活方式。人物应自然、体面、数量适中，动作和服装应符合高端项目气质，不能遮挡建筑主体或造成杂乱。',
    avoid: '避免过度阴郁、过度概念化、强戏剧冲突、脏乱环境、廉价饱和色、过度HDR、过强锐化、塑料CG感、空洞无生活感、人物过多、建筑主体不清晰、过度浮夸的奢华感、销售图缺乏可信度。',
  },
};

export const styleDefinitions: StyleDefinition[] = [mirStyle, luxigonStyle, binyanStyle];

export const STYLE_PRESETS = styleDefinitions;

const STYLE_PRESET_BY_ID = new Map(styleDefinitions.map((style) => [style.id, style]));
const LEGACY_STYLE_ID_MAP: Record<string, string> = {
  mir_atmosphere: 'mir',
  luxigon_drama: 'luxigon',
  binyan_estate: 'binyan',
};

export function getStylePresetById(id: string | null | undefined) {
  if (!id) return null;
  return STYLE_PRESET_BY_ID.get(id) || STYLE_PRESET_BY_ID.get(LEGACY_STYLE_ID_MAP[id]) || null;
}
