export const UPSCALE_NODE_DEFAULTS: Record<string, unknown> = {
  engine: 'magnific_precision_v2',
  scale: 2,
  mode: 'preserve',
  fidelity: 0,
  sharpness: 7,
  denoise: 0,
  detail: 30,
  materialDetail: 7,
  compressionRepair: 0,
  status: 'idle',
  progress: 0,
  history: [],
  tlModel: 'general',
  tlScale: 4,
  mcUpscale: '2x',
  mcOptimized: 'standard',
  mcCreativity: 0,
  mcDetail: 0,
  mcSimilarity: 0,
  mcPromptStr: 0,
  mpUpscale: '2x',
  mpSharpen: 7,
  mpGrain: 7,
  mpUltra: 30,
};
